version: '3.9'

services:
  webserver:
    image: nginx:stable
    restart: always
    ports:
      - "8080:80"
      # - "443:443"
    volumes:
      - ./nginx-dev:/etc/nginx/conf.d
      - wordpress:/var/www/html
      # - ./ssl:/etc/ssl
  
  wordpress:
    image: wordpress:5.9.1-php8.1-fpm
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress: