version: '3.9'

services:

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_DATABASE=wpdocker
      - MYSQL_USER=user
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_PASSWORD=root
    volumes: 
      - ./mariadb:/var/lib/mysql

  wordpress:
    depends_on: 
      - mariadb
    links: 
      - mariadb
    image: wordpress:5.9.1-php8.0-fpm-alpine
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: 12345
      WORDPRESS_DB_NAME: wpdocker
      WORDPRESS_DEBUG: true
    volumes:
      - ./wordpress:/var/www/html:delegated
      - ./wp-content:/var/www/html/wp-content:delegated
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:delegated
  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx-dev:/etc/nginx/conf.d:delegated
      - ./wordpress:/var/www/html:delegated
      - ./wp-content:/var/www/html/wp-content:delegated